language: python
before_install:
  - pip install --upgrade cython
script: 
  - coverage run --source=src test/test_utils.py 
  - coverage run --source=src test/test_scale_correction.py
after_success: coveralls